#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Regenerate site/registry.md from registry.json and registry/entries/*.yaml.

registry.json (built by .github/gen_registry.py from REGISTRY.md) is the
source of truth for LIVE entries. registry/entries/*.yaml carries entries not
yet in the live tables (provisional and reserved). This script only reads;
it never writes back to either source. Run after any change to either input
and commit the regenerated site/registry.md alongside it — the same
discipline gen_registry.py already uses for REGISTRY.md -> registry.json.

Usage:
    python3 site/generate.py [--check]
--check exits 1 if the committed site/registry.md is not what this script
would produce right now, without writing anything (for a future CI wiring;
not itself wired into a workflow by this change).
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("error: PyYAML is required (pip install pyyaml)", file=sys.stderr)
    sys.exit(2)

REPO_ROOT = Path(__file__).resolve().parent.parent
REGISTRY_JSON = REPO_ROOT / "registry.json"
ENTRIES_DIR = REPO_ROOT / "registry" / "entries"
OUTPUT = Path(__file__).resolve().parent / "registry.md"

_HEADER = """\
# Registries

<!-- GENERATED by site/generate.py from registry.json and registry/entries/*.yaml.
     Do not hand-edit — regenerate with `python3 site/generate.py` and commit
     the result. See site/README.md. -->

This mirrors the two registries CPB's IANA Considerations section (draft
§13) defines. **REGISTRY.md in the source repository remains the normative
record**, including the full digest-context detail, Designated Expert notes,
and discriminating vectors for every live entry — this page is the public
summary.

"""


def _row(cells: list[str]) -> str:
    return "| " + " | ".join(c.replace("|", "\\|") for c in cells) + " |"


def render_live_algorithms(data: dict) -> str:
    lines = [
        "## Payload Canonicalization Algorithm Registry — live\n",
        _row(["Name", "Status", "Reference"]),
        _row(["---", "---", "---"]),
    ]
    for name, entry in sorted(data.get("canonicalization_algorithms", {}).items()):
        lines.append(_row([f"`{name}`", entry.get("status", ""), entry.get("reference", "")]))
    return "\n".join(lines) + "\n"


def render_live_artifact_types(data: dict) -> str:
    lines = [
        "\n## Artifact Type Registry — live\n",
        _row(["Name", "Status", "Reference"]),
        _row(["---", "---", "---"]),
    ]
    for name, entry in sorted(data.get("artifact_types", {}).items()):
        lines.append(_row([f"`{name}`", entry.get("status", ""), entry.get("reference", "")]))
    return "\n".join(lines) + "\n"


def load_filed_entries() -> list[dict]:
    entries = []
    if not ENTRIES_DIR.is_dir():
        return entries
    for path in sorted(ENTRIES_DIR.glob("*.yaml")):
        if path.name == "TEMPLATE.yaml":
            continue
        entry = yaml.safe_load(path.read_text(encoding="utf-8"))
        if isinstance(entry, dict):
            entries.append(entry)
    return entries


def render_provisional_and_reserved(entries: list[dict]) -> str:
    filed = [e for e in entries if e.get("status") in ("provisional", "reserved")]
    lines = [
        "\n## Provisional & reserved filings\n",
        "Not yet in the live tables above. See each entry's own file under "
        "`registry/entries/` in the source repository for full detail, open "
        "questions, and the assigned Designated Expert.\n",
        _row(["Name", "Registry", "Status", "Owner", "Open questions"]),
        _row(["---", "---", "---", "---", "---"]),
    ]
    for e in sorted(filed, key=lambda e: e.get("name", "")):
        owner = (e.get("owner") or {}).get("name", "")
        open_qs = len(e.get("open_questions") or [])
        lines.append(_row([
            f"`{e.get('name', '')}`",
            e.get("target_registry", ""),
            e.get("status", ""),
            owner,
            f"{open_qs} open" if open_qs else "none",
        ]))
    return "\n".join(lines) + "\n"


def render(data: dict, entries: list[dict]) -> str:
    return (
        _HEADER
        + render_live_algorithms(data)
        + render_live_artifact_types(data)
        + render_provisional_and_reserved(entries)
    )


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    check = "--check" in argv

    data = json.loads(REGISTRY_JSON.read_text(encoding="utf-8"))
    entries = load_filed_entries()
    rendered = render(data, entries)

    if check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        if current != rendered:
            print(f"error: {OUTPUT} is stale — run `python3 site/generate.py`", file=sys.stderr)
            return 1
        print(f"{OUTPUT}: up to date")
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
