# SPDX-License-Identifier: BSD-3-Clause
"""CPB reference library — live construction and historical compatibility.

Implements only the mechanisms defined in draft-mih-sokolov-scitt-payload-binding:
  §4    Live jcs plus historical jcs-n digest evaluation
  §5    Derived-identifier construction, evaluation, and verification
  §8    Typed-reference construction, evaluation, and verification
  §14   Registry snapshot lookup (machine-readable registry.json)
  check Grammar conformance checker (P/R rules, Phase 1)

No payload semantics from any specific profile are included here.
"""
from .canonicalize import (
    FloatInDigestError,
    UnsafeIntegerError,
    JsonWireFormatError,
    MAX_SAFE_INTEGER,
    normalize,
    jcs,
    jcs_n,
    raw_digest,
    canonical_digest,
    canonical_digest_json,
)
from .derive_id import (
    derive_id,
    derive_id_json,
    evaluate_derived_id,
    evaluate_derived_id_json,
    verify_carried_id,
    CarriedIdMismatch,
)
from .typed_ref import (
    ArtifactDigestContext,
    ArtifactTypeDefinition,
    TypedRef,
    ArtifactTypeRegistryEntry,
    TypedRefError,
    ContextMismatchError,
    DigestContextResolutionError,
    RepresentationMismatchError,
    DigestAlgorithmMismatchError,
    PurposeMismatchError,
    PurposeRequiredError,
    UnsupportedDigestContextError,
    UnsupportedRepresentationError,
    make_typed_ref,
    make_typed_ref_json,
    evaluate_typed_ref_digest,
    verify_typed_ref,
    verify_typed_ref_json,
    hex_to_raw,
    raw_to_hex,
)
from .vintage import (
    JCS_N_WITHDRAWAL_CUTOFF,
    VintageEvidenceVerifier,
    WithdrawnAlgorithmError,
    VintageEvidenceError,
)
from .registry import (
    VERDICT_VERIFIED,
    VERDICT_RESERVED,
    VERDICT_UNKNOWN_ID,
    VERDICT_ID_UNKNOWN_TO_SNAPSHOT,
    SnapshotIntegrityError,
    RegistrySnapshot,
    compute_snapshot_sha256,
)

from .check import (
    Verdict,
    Violation,
    CheckResult,
    check,
    check_p,
    check_r,
)
from .cose_refs import (
    CborMap,
    CborSimple,
    CborTag,
    CoseSign1,
    CpbRefsError,
    CpbRefsLocationError,
    DuplicateCborKeyError,
    MalformedCborError,
    cose_signature1_structure,
    decode_cose_sign1,
    encode_deterministic_cbor,
    extract_cpb_refs,
)

__all__ = [
    "ArtifactDigestContext",
    "ArtifactTypeDefinition",
    "FloatInDigestError",
    "UnsafeIntegerError",
    "JsonWireFormatError",
    "MAX_SAFE_INTEGER",
    "normalize",
    "jcs",
    "jcs_n",
    "raw_digest",
    "canonical_digest",
    "canonical_digest_json",
    "derive_id",
    "derive_id_json",
    "evaluate_derived_id",
    "evaluate_derived_id_json",
    "verify_carried_id",
    "CarriedIdMismatch",
    "TypedRef",
    "ArtifactTypeRegistryEntry",
    "TypedRefError",
    "ContextMismatchError",
    "DigestContextResolutionError",
    "RepresentationMismatchError",
    "DigestAlgorithmMismatchError",
    "PurposeMismatchError",
    "PurposeRequiredError",
    "UnsupportedDigestContextError",
    "UnsupportedRepresentationError",
    "make_typed_ref",
    "make_typed_ref_json",
    "evaluate_typed_ref_digest",
    "verify_typed_ref",
    "verify_typed_ref_json",
    "hex_to_raw",
    "raw_to_hex",
    "CborMap",
    "CborSimple",
    "CborTag",
    "CoseSign1",
    "CpbRefsError",
    "CpbRefsLocationError",
    "DuplicateCborKeyError",
    "MalformedCborError",
    "cose_signature1_structure",
    "decode_cose_sign1",
    "encode_deterministic_cbor",
    "extract_cpb_refs",
    "JCS_N_WITHDRAWAL_CUTOFF",
    "VintageEvidenceVerifier",
    "WithdrawnAlgorithmError",
    "VintageEvidenceError",
    "VERDICT_VERIFIED",
    "VERDICT_RESERVED",
    "VERDICT_UNKNOWN_ID",
    "VERDICT_ID_UNKNOWN_TO_SNAPSHOT",
    "SnapshotIntegrityError",
    "RegistrySnapshot",
    "compute_snapshot_sha256",
    # Grammar checker (Phase 1)
    "Verdict",
    "Violation",
    "CheckResult",
    "check",
    "check_p",
    "check_r",
]
